---
- name: AWS Instance Creation
  hosts: localhost
  connection: local
  gather_facts: True
  remote_user: ec2-user
  tasks:
    - name: Create an EC2 instance
      ec2:
        key_name: Sushma_Oregon
        region: "us-west-2"
        group_id: "sg-0f424a77a6a01959f"
        instance_type: "t2.micro"
        image: "ami-0cb72367e98845d43"
        wait: yes
        instance_tags: '{"Name":"Chatops","Type":"Chatops"}'
        vpc_subnet_id: "subnet-46afc40d"
        assign_public_ip: yes
      register: ec2
    - name: Display IP's of  new instance
      debug:
        msg: "Newly launched instance Public IP is {{ ec2.instances[0].public_ip }}, private IP is {{ ec2.instances[0].private_ip }}, Instance Type is {{ ec2.instances[0].instance_type }}"
    - name: Add the newly created EC2 instance(s) to host group
      lineinfile:
              path: /home/scripts/inventory
              insertafter: '\[Test\]'
              line: "{{ ec2.instances[0].private_ip }} ansible_user=ec2-user ansible_ssh_private_key_file=/home/Sushma.pem"
              state: present
     #with_items: "{{ ec2.instances }}"
